apiVersion: apps/v1
kind: Deployment
metadata:
  name: fursorger-deployment
  labels:
    app: fursorger
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fursorger
  template:
    metadata:
      labels:
        app: fursorger
    spec:
      containers:
        - name: fursorger
          image: nonbiri/fursorger:latest
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Service
metadata:
  name: fursorger-service
spec:
  selector:
    app: fursorger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
